### ISSUE TITLE
Work behind reverse proxy

### ISSUE THREAD

**Issue by zoic21** [MedAziz11/Uptime-Kuma-Web-API#1]
Hello,

To begin thank for your work, with your rest api I can use kuma !!!!

I try to make it work but it's seem there is an issue when we use reverse proxy (on synology for me), when I try to get access-token it's redirect me from port 443 to port 80. On app log I got : 

![image](https://user-images.githubusercontent.com/1536036/207888373-37c20332-ed56-46d4-adea-e686d7de13d1.png)

And here curl details : 
![image](https://user-images.githubusercontent.com/1536036/207888673-9bac1251-1f89-465f-9bc3-208a01ec8347.png)

I do something wrong or it's not supported ?

Thank in advance,

**Comment by MedAziz11** [comment]
actually ive never used synology but ive tried it with Traefik and its working completely fine. can i see more of your configs ?

**Comment by zoic21** [comment]
Hello,
Thank for your reply. On docker side I just redirect port 8000 to 58752 : 
![image](https://user-images.githubusercontent.com/1536036/208122806-090f9516-a406-47e6-b098-c5583e730350.png)

On reverse proxy side I just have this : 
![image](https://user-images.githubusercontent.com/1536036/208123004-838e3380-8fca-451f-84fb-bb21517b3448.png)

Take url and reverse proxy to docker port.

Are they any configuration to do with ENV variable on docker for reverse proxy ?

**Comment by Kovah** [comment]
The api works behind reverse proxies without issues for me.
Try adding `X-Forwarded-Proto` to the header configuration for Synology.

<img width="635" alt="Bildschirm­foto 2023-02-01 um 20 14 57" src="https://user-images.githubusercontent.com/1816101/216140887-66d7c603-1293-4565-ad59-28bce9e1605a.png">

**Comment by elliotmatson** [comment]
I was seeing this issue, and #12 solved it for me

**Comment by 123dev** [comment]
> actually ive never used synology but ive tried it with Traefik and its working completely fine. can i see more of your configs ?

How's your traefik setup?
Are you using http?
because it doesn't seem to work with https

The app doesn't seem to honor X-Forwarded-Proto
the redirect to access token is always http

Thanks
