### ISSUE TITLE
Question: Possible to toggle Maintenance mode with this wrapper?

### ISSUE THREAD

**Issue by hugalafutro** [MedAziz11/Uptime-Kuma-Web-API#10]
Hi,
sorry not sure where to ask, I vaguely understand what this does, but is there any endpoint to trigger a monitor's maintenance mode in uptime-kuma on and off via curl? Apologies if it's apparent from the description and/or the picture I'm a dum dum.

**Comment by MedAziz11** [comment]
added in the last commit.
