### ISSUE TITLE
exec /app/entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by alienbuild** [MedAziz11/Uptime-Kuma-Web-API#36]
Not sure if i'm missing a step here but when spinning up the docker image, using the example provided, the `uptime-kuma` starts up fine, but `api-1` errors with: 
```
exec /app/entrypoint.sh: no such file or directory
```

If i inspect the files though I can see that the folder `app` exists and `entrypoint.sh` file also exists. I'm using docker desktop for Windows (with WSL2) 

Any advice appreciated

Thanks

**Comment by MedAziz11** [comment]
are you using vscode ?

**Comment by MedAziz11** [comment]
okk open your entrypoint.sh end change end of line sequence to LF

**Comment by alienbuild** [comment]
Thanks!
