### ISSUE TITLE
Assign tags to monitor

### ISSUE THREAD

**Issue by kj187** [MedAziz11/Uptime-Kuma-Web-API#4]
First of all, nice work! Thanks!
But currently it is not possible to assign tags to a monitor or is it possible?
Cant find any tag key in the monitor schema API for that ;(

**Comment by MedAziz11** [comment]
ill add this feature as fast as i can.

**Comment by travisghansen** [comment]
I'm building an integration with https://github.com/stakater/IngressMonitorController and uptime-kuma using this and I don't see how this is supposed to be done in the swagger docs. Is this part of the post/patch of a monitor or something else?
