### ISSUE TITLE
Make ACCESS_TOKEN_EXPIRE configurable via env

### ISSUE THREAD

**Issue by Kovah** [MedAziz11/Uptime-Kuma-Web-API#7]
It would be very helpful if the access token expiry could be configured via a env setting. At the moment it expires every 8 days which makes it even more complicated to use in automated systems without overloading actions with additional requests to get a token, or by implementing scheduled renews of the auth token.

**Comment by MedAziz11** [comment]
thnks for the amazing contribution, ill implement it nice idea
